#!/bin/bash
#EXT_TEST TEST_FILE_MINVER 15.0
#EXT_TEST TEST_FILE_DESC "Tests custom naming of checkpoint directories and files"
#EXT_TEST DEP "coreTestElement.coreTestComponent"
#EXT_TEST TIMEOUT 120

# --checkpoint-name-format command line option
# Set the format for filenames generated by checkpointing using three tokens:
# %p – prefix specified by –checkpoint-prefix
# %t – simulated time of the checkpoint
# %n – checkpoint number

# Run in unique directory to avoid having spurious files in the test directory
rundir=sst_checkpoint_name_format.$$
rm -Rf $rundir
mkdir $rundir
pushd $rundir

# Check 1: create locally
pfx=test1
sst  --checkpoint-prefix=${pfx} --checkpoint-name-format="%n_%t/cpt" --checkpoint-sim-period=10us ../cli-sdl.py
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "ERROR : $retVal"
    exit $retVal
fi
if [ ! -d "$pfx" ]; then
    echo "ERROR : Output directory ${pfx} does not exist!"
    exit 1
fi
cptfiles=(\
 "$pfx/1_10000000/cpt.sstcpt" \
 "$pfx/1_10000000/cpt_0_0.bin" \
 "$pfx/1_10000000/cpt_globals.bin"\
)
for cptfile in "${cptfiles[@]}"; do
    if [ ! -e "$cptfile" ]; then
        echo "ERROR missing checkpoint file $cptfile"
        exit 2
    fi
done

# Check 2: create under --output-directory
pfx=test2pfx
sst  --output-directory=test2 --checkpoint-prefix=${pfx} --checkpoint-name-format="%n_%t/%p_cpt" --checkpoint-sim-period=10us ../cli-sdl.py
retVal=$?
if [ $retVal -ne 0 ]; then
    echo "ERROR : $retVal"
    exit $retVal
fi
if [ ! -d "test2/$pfx" ]; then
    echo "ERROR : Output directory ${pfx} does not exist!"
    exit 1
fi
cptfiles=(\
 "test2/$pfx/1_10000000/${pfx}_cpt.sstcpt" \
 "test2/$pfx/1_10000000/${pfx}_cpt_0_0.bin" \
 "test2/$pfx/1_10000000/${pfx}_cpt_globals.bin"\
)
for cptfile in "${cptfiles[@]}"; do
    if [ ! -e "$cptfile" ]; then
        echo "ERROR missing checkpoint file $cptfile"
        exit 2
    fi
done

# Cleaning up
popd
rm -Rf $rundir

# ensure asynchronous rm -rF completed
wait

# All good
echo "PASS"
exit 0
